services:
  backend:
    build:
      context: ./publishing-backend/
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./publishing-backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
  
  frontend:
    build:
      context: ./publishing-frontend/
      dockerfile: Dockerfile
    volumes:
      - ./publishing-frontend:/app
      - /app/node_modules
    command: npm start

  database:
    image: postgres:17-alpine
    env_file: 
      - .env
    ports:
      - "5432:5432"
        
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
